# Regresión Líneal Polinomial


In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
 #pip install scikit-learn


In [3]:
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
boston = datasets.load_boston()


In [5]:

boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
print('Nombre de columnas:')
print(boston.feature_names)

Nombre de columnas:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [7]:
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [8]:
print("Informacion en el dataset:")
print(boston.keys())

Informacion en el dataset:
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])


In [9]:
print("Características del dataset:")
print(boston.DESCR)


Características del dataset:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per 

In [10]:
print("Cantidad de datos:")
print(boston.data.shape)

Cantidad de datos:
(506, 13)


In [13]:
# Seleccionamos como valor de la X la columna numero 6 (RM)
X = boston.data[:,np.newaxis, 5]
X

array([[6.575],
       [6.421],
       [7.185],
       [6.998],
       [7.147],
       [6.43 ],
       [6.012],
       [6.172],
       [5.631],
       [6.004],
       [6.377],
       [6.009],
       [5.889],
       [5.949],
       [6.096],
       [5.834],
       [5.935],
       [5.99 ],
       [5.456],
       [5.727],
       [5.57 ],
       [5.965],
       [6.142],
       [5.813],
       [5.924],
       [5.599],
       [5.813],
       [6.047],
       [6.495],
       [6.674],
       [5.713],
       [6.072],
       [5.95 ],
       [5.701],
       [6.096],
       [5.933],
       [5.841],
       [5.85 ],
       [5.966],
       [6.595],
       [7.024],
       [6.77 ],
       [6.169],
       [6.211],
       [6.069],
       [5.682],
       [5.786],
       [6.03 ],
       [5.399],
       [5.602],
       [5.963],
       [6.115],
       [6.511],
       [5.998],
       [5.888],
       [7.249],
       [6.383],
       [6.816],
       [6.145],
       [5.927],
       [5.741],
       [5.966],
       [

In [14]:
y = boston.target
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [14]:
## Cargar el modelo:

In [15]:

from sklearn.preprocessing import PolynomialFeatures

In [16]:
# se define el grado de polinomio
poli_reg = PolynomialFeatures(degree= 2)

In [17]:
# se transforman las características existentes en características de mayor grado
X_train_poli = poli_reg.fit_transform(X_train)
X_test_poli = poli_reg.fit_transform(X_test)


In [18]:

pr = linear_model.LinearRegression()


In [19]:
pr.fit(X_train_poli, y_train)

LinearRegression()

In [20]:
y_pred = pr.predict(X_test_poli)
y_pred

array([17.39496769, 22.07339597, 16.77241048, 60.78637556, 18.30693547,
       22.45173143, 19.97170583, 49.2770551 , 19.54580053, 26.71749237,
       26.19611581, 20.76484819, 17.67336921, 20.15672276, 25.04734855,
       32.08433895, 16.00586052, 16.7587201 , 30.61768785, 32.19769822,
       17.23831256, 50.28606292, 18.59990377, 23.85847119, 24.28119587,
       22.31217483, 35.47733597, 18.31941572, 30.79402248, 16.72246991,
       22.10074547, 15.00611975, 20.59343386, 15.95470196, 20.62588523,
       22.15560249, 20.0715049 , 36.25898436, 18.17730612, 23.03282708,
       20.87225516, 22.41438759, 25.84383923, 18.90525541, 17.97290187,
       16.74508239, 16.76784117, 24.1460961 , 21.46760116, 23.45553749,
       17.08196889, 15.59400663, 24.00171013, 33.11805592, 27.02413378,
       22.23828305, 26.98855018, 18.8445383 , 18.2387125 , 23.58546387,
       18.24488533, 17.37377602, 40.30054675, 22.83031982, 19.91837753,
       31.30131127, 18.74439652, 23.83810212, 26.34551844, 21.50

In [21]:

y_test


array([19.3, 13.1, 18.5, 21.9, 21.7, 21.6, 17. , 48.3, 14.5, 33.1, 26.5,
       19.4, 19.8, 29.6, 28.6, 32.7,  7. , 19.4, 32.9, 35.4, 13.1, 50. ,
        8.4, 24.8, 23.3, 17.1, 43.5, 22.6, 37.3, 17.4, 24.7, 13.8, 11.7,
       14.4, 17.8, 23.9, 15.2, 43.1, 19.3, 29.1, 23. , 24.2, 23.7, 24.3,
       19.9, 13.9, 26.4, 22.4, 23. , 14.1, 23.1,  8.8, 24.1, 15. , 27.5,
       25. , 28.2, 20.3, 22. , 24.4, 18.8, 18.2, 39.8,  9.6, 21.5, 34.7,
        8.8, 32.5, 13.3, 22.2, 37.6, 19.6, 18.9,  8.3, 20. , 23.1, 30.1,
        6.3, 15.2, 18.5, 14.1, 31.7, 21.6, 25.3, 20. , 34.9, 20.7, 23.3,
        7.2, 46. , 17.1, 23.2, 24.1, 23.9, 14.3, 16.1, 20.6, 24. , 19.5,
       24.5, 19.9, 48.5])

In [22]:

print("Valor de pendiente o coeficiente 'a':")
print(pr.coef_)

Valor de pendiente o coeficiente 'a':
[  0.         -28.22955141   2.92611871]


In [23]:
print("Precisión del modelo: ")
print(pr.score(X_train_poli, y_train))

Precisión del modelo: 
0.5618426357965204
