##Regresión Líneal Múltiple

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
 #pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
boston = datasets.load_boston()


In [5]:
boston.data


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
print('Nombre de columnas:')
print(boston.feature_names)


Nombre de columnas:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [7]:
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [8]:
print("Informacion en el dataset:")
print(boston.keys())

Informacion en el dataset:
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])


In [9]:
print("Características del dataset:")
print(boston.DESCR)

Características del dataset:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per 

In [10]:
print("Cantidad de datos:")
print(boston.data.shape)

Cantidad de datos:
(506, 13)


In [11]:
# Seleccionamos como valor de la X las columnas desde la 5 a la 7:
X = boston.data[:, 5:8]

In [12]:
y = boston.target

In [13]:
from sklearn.model_selection import train_test_split
# Separo los datos de "train" entrenamiento y "test" prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
lr_multiple = linear_model.LinearRegression()


In [16]:
lr_multiple.fit(X_train, y_train)

LinearRegression()

In [17]:
y_pred = lr_multiple.predict(X_test)
y_pred

array([27.85488546, 24.98015601, 14.92233543, 18.27359273, 23.55888752,
       22.97474737, 21.70802163, 25.71086254, 22.44315603, 15.9493327 ,
       18.8469667 , 14.9263684 , 16.81746592, 24.57885181, 20.01615663,
       27.08486346, 21.70980237, 35.07584077, 25.81891476, 33.80539214,
       25.33558793, 17.83828972, 26.52588077, 17.59985737, 26.07869893,
       24.00597189, 21.04975287, 25.58976487, 20.33892776, 26.26219084,
       27.25587751, 18.71838412, 23.81930214, 22.00615289, 21.96795611,
       19.90339724, 22.36633355, 30.086061  , 21.71238722, 22.48035943,
       27.41038587,  5.9783075 , 23.35803062, 11.26920931, 22.42689883,
       26.31984047, 27.35862425, 17.70210652, 37.86018173, 21.14033529,
       19.32568315, 20.96411874, 24.71374644, 23.60198944, 20.34228313,
       22.62274624, 24.65807538, 13.81743336, 19.81016199, 21.81034453,
       23.38571287, 25.87534865, 21.01812718, 18.428436  , 19.52681575,
       23.84403944, 30.51669357, 21.37361626, 26.92382544, 19.56

In [18]:

y_test

array([25. , 13.4, 13.1, 13.2, 22.3, 22.9, 14.9, 24.4, 19.3, 15. , 18.7,
       23.1, 11.7, 22.9, 20.7, 26.5, 22.3, 44. , 25. , 50. , 24. , 17.8,
       23.1, 18.8, 25. , 23.2, 20. , 22.8, 17.5, 23.7, 22. , 18.2, 13.4,
       17.7, 21.7, 20.4, 11.8, 37.2, 21.2, 36.2, 25. , 17.9, 24.1, 20. ,
       23.2, 23.5, 10.4, 19.6, 50. , 14.9, 21.5, 23.8, 25.1, 15.2, 20.5,
       21.2, 22.2, 12.3, 16.8, 18. , 20.8, 22.8, 21.4, 17.4, 21.8, 28.7,
       31.2, 24.4, 23.3, 20. , 27.5, 21.4,  7. , 24.5, 20. , 29.6, 14. ,
       24.7, 15.3, 30.5, 19.1, 20.3, 42.3, 17.8, 19.7, 19.1, 32.5, 35.2,
       12.8, 18.5, 14.3, 32. , 26.4, 19.3, 22.8, 24.8, 17.4, 17. , 26.7,
       20.4, 23. , 29.4])

In [19]:

print('DATOS DEL MODELO REGRESIÓN LINEAL MULTIPLE')
print()
print('Valor de las pendientes o coeficientes "a":')
print(lr_multiple.coef_)
print('Valor de la intersección o coeficiente "b":')
print(lr_multiple.intercept_)

DATOS DEL MODELO REGRESIÓN LINEAL MULTIPLE

Valor de las pendientes o coeficientes "a":
[ 8.7782683  -0.09633432 -0.42839098]
Valor de la intersección o coeficiente "b":
-24.348409270999554


In [20]:
print("Precisión del modelo:")
print(lr_multiple.score(X_train, y_train))

Precisión del modelo:
0.5596236303502309
