 # Support Vector Regression (SVR)

In [1]:
import warnings
warnings.filterwarnings("ignore")

https://scikit-learn.org/stable/install.html

In [2]:
 #pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
import pandas as pd

In [4]:

boston = datasets.load_boston()


In [5]:

boston.data


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
print('Nombre de columnas:')
print(boston.feature_names)


Nombre de columnas:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [7]:
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [8]:
print("Informacion en el dataset:")
print(boston.keys())


Informacion en el dataset:
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])


In [9]:
print("Características del dataset:")
print(boston.DESCR)

Características del dataset:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per 

In [10]:
print("Cantidad de datos:")
print(boston.data.shape)

Cantidad de datos:
(506, 13)


In [11]:
# Seleccionamos como valor de la X la columna 6 (RM):
X = boston.data[:, np.newaxis, 5]

In [12]:
y = boston.target


In [13]:
from sklearn.model_selection import train_test_split
# Separo los datos de "train" entrenamiento y "test" prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [14]:
from sklearn.svm import SVR

In [15]:
svr = SVR(kernel="linear", C=1.0, epsilon=0.2)

In [16]:
svr.fit(X_train, y_train)

SVR(epsilon=0.2, kernel='linear')

In [17]:
y_pred = svr.predict(X_test)
y_pred


array([21.40635099, 23.91840209, 26.72065403, 30.88322245, 22.83014891,
       16.25528594, 25.89539537, 20.59922988, 13.53465298,  7.69436091,
       16.44573024, 25.9588768 , 21.16149403, 14.82241925, 17.46143321,
       17.84232183, 26.49393462, 24.50787256, 19.98255308, 19.78304   ,
       18.65851171, 40.68656985, 23.54658225, 25.61426329, 19.08474421,
       26.33069664, 18.97591889, 19.02126277, 22.96618055, 23.80050799,
       21.61493285,  3.25066042, 22.86642401, 18.44086108, 21.45169488,
       20.2455476 , 31.04646042, 27.53684391, 26.62089749, 18.23227922,
       20.17299739, 23.09314342, 20.71712398, 17.53398342, 23.51030714,
       31.39107393, 24.06350251, 29.02412326, 16.23714838, 16.48200535,
       14.18760489, 24.07257129, 23.718889  , 33.01438493, 44.65869396,
       19.54725181, 22.41298519, 16.62710577, 26.0767709 , 27.88145742,
       18.81268091, 20.31809781, 22.96618055, 21.2884569 , 13.82485383,
       22.05023413, 22.0593029 , 25.27871856, 15.8834661 , 32.45

In [18]:
y_test


array([20.8, 22.6, 29. , 34.9, 16.1, 23.1, 22.8, 23.2, 13.1, 17.9, 17.6,
       28.7, 21. ,  7. , 16.2,  8.5, 16.4, 29.1, 20.1, 21.7, 10.2, 44.8,
       23.1, 29.1, 18.6, 50. , 20.4, 23.8, 21.2, 12.1, 21.4, 13.8, 14.9,
       16.6, 23.3, 22.9, 33.8, 31.6, 22.8, 20.3, 20.3, 24.4, 24.4, 12.7,
       23. , 32.7, 24.5, 29.8, 13.6, 15.4, 20. ,  7.2, 21.7, 33.4, 50. ,
        8.4, 19.9, 15.7, 15.2, 32. , 10.8, 23.2, 23. , 22.7, 12. , 24.7,
       17.8, 23.8,  8.5, 31.5, 13.4, 17.1, 18.3, 11.7, 23.1, 15.6, 20.4,
       15.1, 17.2, 36.5, 21.7, 19.6, 21.8,  7.4, 18.7, 31. , 50. , 28.1,
       43.5, 22.1, 13.1,  5. , 13.3, 20.2, 39.8, 20.8, 23.7, 19.5, 19.1,
       50. , 18.4, 17.2])

In [19]:
print("DATOS DEL MODELO VECTORES DE SOPORTE REGRESIÓN")
print()
print("Precisión del modelo:")
print(svr.score(X_train, y_train))

DATOS DEL MODELO VECTORES DE SOPORTE REGRESIÓN

Precisión del modelo:
0.46808883724359807


In [20]:
# Seleccionamos todas las columnas del data
X = boston.data
